language: node_js
node_js:
  - "4"
  - "6"
  - "8"
before_install:
  - if [[ `npm -v` < 5.3 ]]; then npm install -g npm@5.3.x; fi
script:
  - npm test
  - npm run build
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
